"""Observe only the confirmed opening of an already-published synthetic copy.

The post-publication fixture bypasses copying, not the real open confirmation,
identity checks, window creation or production dialog cleanup. No keys or
confirmation answers are generated by this native probe.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import signal
import sys
import time
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from PySide6.QtCore import QEvent, QObject, QTimer
from PySide6.QtGui import QAction
from PySide6.QtWidgets import QApplication, QDialog
from shiboken6 import isValid

from app.core.project_migration import read_migration_copy
from app.gui import project_migration_dialog as migration
from app.gui.main_window import MainWindow
from app.gui.theme import apply_theme
from tools.probe_history_restore import app_digest
from tools.probe_project_checkpoint_gui import close, window_for


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--copy", type=Path, required=True)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--seconds", type=int, default=300)
    args = parser.parse_args()
    assert os.environ.get("QT_QPA_PLATFORM") == "cocoa"
    output = args.output.resolve()
    output.mkdir(exist_ok=False)
    reviewed = read_migration_copy(args.copy)
    source = args.source.resolve()
    source_before = hashlib.sha256(source.read_bytes()).hexdigest()
    app = QApplication([])
    app.setQuitOnLastWindowClosed(False)
    apply_theme(app)
    owner = window_for(output, "visibility")
    owner.project_files.set_project_root(source.parent)
    owner.open_file(source)
    owner.setWindowTitle("SYNTHETIC migration owner")
    tracked = [owner]
    dialog = migration.ProjectMigrationDialog(owner)
    dialog.result = reviewed.copy
    dialog.project_label.setText("Retained synthetic copy: " + str(reviewed.copy.directory))
    dialog.status.setText("Published-copy fixture; use the real separate open confirmation.")
    if reviewed.kind != "source-copy":
        dialog.source.addItem("Block (saved copy, no draft)", None)
    else:
        for name, _ in reviewed.copy.files:
            if Path(name).suffix.lower() in {".tex", ".ltx"}:
                dialog.source.addItem(name, name)
    dialog._controls()
    states, events, errors = [], [], []
    start, before = time.monotonic(), app_digest()
    timed_out = interrupted = False

    def window_state(window):
        session = getattr(window, "block_session", None)
        handle = window.windowHandle()
        return {"id": id(window), "class": type(window).__name__,
                "title": window.windowTitle(), "visible": window.isVisible(),
                "active": window.isActiveWindow(), "exposed": bool(handle and handle.isExposed()),
                "project": str(session.project_dir) if session else None,
                "compile_authorized": sorted(map(str, getattr(window, "compile_authorized_roots", ()))),
                "status": window.statusBar().currentMessage() if isinstance(window, MainWindow) else None}

    def observe():
        nonlocal timed_out
        try:
            windows = [w for w in app.topLevelWidgets() if isValid(w) and isinstance(w, MainWindow)]
            value = {"windows": sorted((window_state(w) for w in windows), key=lambda w: w["id"]),
                     "dialog_valid": isValid(dialog), "opened": id(dialog.opened) if dialog.opened else None}
            if isValid(dialog):
                value.update(dialog_visible=dialog.isVisible(), busy=dialog.busy,
                             operation=getattr(dialog, "operation", None), closing=dialog.closing,
                             cancelled=dialog.cancel.is_set(), status=dialog.status.text())
            if not states or value != states[-1]["value"]:
                item = {"seconds": round(time.monotonic() - start, 3), "value": value}
                states.append(item)
                for w in windows:
                    if w.isVisible():
                        w.grab().save(str(output / f"state-{len(states):03d}-{id(w)}.png"))
                (output / "live.json").write_text(json.dumps(item, ensure_ascii=False, indent=2))
                print(json.dumps(item, ensure_ascii=False), flush=True)
            if time.monotonic() - start > args.seconds:
                timed_out = True
                app.quit()
        except Exception as exc:
            errors.append(repr(exc))
            app.quit()

    class Observer(QObject):
        def eventFilter(self, watched, event):
            if isinstance(watched, MainWindow) and not any(w is watched for w in tracked):
                tracked.append(watched)
            if isinstance(watched, (MainWindow, QDialog)) and event.type() in {
                    QEvent.Type.Show, QEvent.Type.Hide, QEvent.Type.Close,
                    QEvent.Type.WindowActivate, QEvent.Type.WindowDeactivate}:
                events.append({"seconds": round(time.monotonic() - start, 3),
                               "id": id(watched), "class": type(watched).__name__,
                               "event": event.type().name})
            return super().eventFilter(watched, event)

    observer = Observer(app)
    app.installEventFilter(observer)
    timer = QTimer(observer)
    timer.timeout.connect(observe)
    timer.start(100)
    finish = QAction("Finish visibility QA", owner)
    finish.triggered.connect(app.quit)
    owner.menuBar().addMenu("Synthetic QA").addAction(finish)

    def show_retained():
        with patch.object(migration, "ProjectMigrationDialog", return_value=dialog):
            migration.show_project_migration(owner)

    def interrupt(*_):
        nonlocal interrupted
        interrupted = True
        app.quit()

    signal.signal(signal.SIGINT, interrupt)
    owner.show()
    QTimer.singleShot(0, show_retained)
    app.exec()
    timer.stop()
    observe()
    app.removeEventFilter(observer)
    for widget in list(app.topLevelWidgets()):
        if isValid(widget) and isinstance(widget, QDialog):
            widget.reject()
    windows = [w for w in app.topLevelWidgets() if isValid(w) and isinstance(w, MainWindow)]
    for window in windows:
        close(window)
    app.sendPostedEvents(None, QEvent.Type.DeferredDelete)
    read_migration_copy(args.copy, expected=reviewed)
    report = {"synthetic_only": True, "app_sha256": before, "app_sha256_after": app_digest(),
              "source_unchanged": hashlib.sha256(source.read_bytes()).hexdigest() == source_before,
              "copy_unchanged": True, "states": states, "events": events, "errors": errors,
              "timeout": timed_out, "interrupted": interrupted,
              "windows_destroyed": [not isValid(w) for w in tracked]}
    (output / "report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2))
    return int(bool(errors or timed_out or interrupted or not all(report["windows_destroyed"])))


if __name__ == "__main__":
    raise SystemExit(main())
