#!/usr/bin/env python3
"""Validate that source, checked-in release metadata, and local assets agree."""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

import update_release_site


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "release" / "release-manifest.json"
SITE_PATH = ROOT / "website" / "release.json"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def fail(problems: list[str], message: str) -> None:
    problems.append(message)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--require-tag-at-head", action="store_true")
    args = parser.parse_args()

    problems: list[str] = []
    try:
        manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
        generated = update_release_site.generated_release_data(manifest)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"Release consistency FAILED: {exc}", file=sys.stderr)
        return 1

    try:
        site = json.loads(SITE_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        print(f"Release consistency FAILED: {exc}", file=sys.stderr)
        return 1

    for key in (
        "repository",
        "version",
        "tag",
        "channel",
        "release_name",
        "github_repository_public",
        "github_release_published",
    ):
        if site.get(key) != generated.get(key):
            fail(problems, f"website/release.json {key} disagrees with generated release data")
    if site != generated:
        fail(problems, "website/release.json must be generated by tools/update_release_site.py")

    for document in manifest.get("documents", []):
        path = ROOT / "release" / str(document)
        if not path.is_file():
            fail(problems, f"missing release document: {path.relative_to(ROOT)}")

    for entry in manifest.get("assets", []):
        if not isinstance(entry, dict):
            fail(problems, "manifest has a non-object asset")
            continue
        path = ROOT / "release" / str(entry.get("name", ""))
        if not path.is_file():
            fail(problems, f"missing release asset: {path.relative_to(ROOT)}")
            continue
        expected = entry.get("sha256")
        actual = sha256(path)
        if expected != actual:
            fail(problems, f"sha256 mismatch: {path.name}")

    version = generated["version"]
    for document in ("INSTALLATION.md", "KNOWN_LIMITATIONS.md", "RELEASE_NOTES.md"):
        text = (ROOT / "release" / document).read_text(encoding="utf-8")
        if str(version) not in text:
            fail(problems, f"{document} does not mention version {version}")

    if args.require_tag_at_head:
        tag = str(generated["tag"])
        try:
            tag_commit = subprocess.check_output(["git", "rev-parse", f"{tag}^{{commit}}"], cwd=ROOT, text=True).strip()
            head_commit = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
        except subprocess.CalledProcessError as exc:
            fail(problems, f"cannot resolve release tag: {exc}")
        else:
            if tag_commit != head_commit:
                fail(problems, f"{tag} must resolve to HEAD before release")

    if problems:
        print("Release consistency FAILED:", file=sys.stderr)
        print("\n".join(f"- {problem}" for problem in problems), file=sys.stderr)
        return 1
    print(f"Release consistency PASS: {generated['tag']} ({generated['repository']})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
